easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
        - Engelsystem\Entity\AngelType
        - Engelsystem\Entity\EventConfig
        - Engelsystem\Entity\Group
        - Engelsystem\Entity\LogEntries
        - Engelsystem\Entity\Messages
        - Engelsystem\Entity\NeededAngelTypes
        - Engelsystem\Entity\News
        - Engelsystem\Entity\NewsComment
        - Engelsystem\Entity\Permission
        - Engelsystem\Entity\Questions
        - Engelsystem\Entity\Room
        - Engelsystem\Entity\Shift
        - Engelsystem\Entity\ShiftEntry
        - Engelsystem\Entity\ShiftTypes
        - Engelsystem\Entity\User
        - Engelsystem\Entity\UserAngelTypes
        - Engelsystem\Entity\UserDriverLicenses
        - Engelsystem\Entity\UserWorkLog